# Generated by Django 5.2.7 on 2025-11-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='level',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('LABORAL', 'Laboral')], default='BASICO', max_length=10),
        ),
    ]
