# Generated by Django 5.2.7 on 2025-11-07 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_coursename_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('LABORAL', 'Laboral')], default='BASICO', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('category', 'code')},
        ),
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejes', to='core.subject')),
            ],
        ),
    ]
