# Generated by Django 5.2.7 on 2025-11-09 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_subject_category_subject_code_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('ocupation', models.CharField(max_length=20)),
                ('collage_level', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('birth_date', models.DateField()),
                ('bapDiag', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('grade', models.CharField(max_length=40)),
                ('etnia', models.CharField(blank=True, max_length=40, null=True)),
                ('nivel', models.CharField(choices=[('BASICO', 'Básico'), ('LABORAL', 'Laboral')], default='BASICO', max_length=10)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.course')),
                ('parents', models.ManyToManyField(blank=True, related_name='students', to='directorApp.parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
