# Generated by Django 5.2.7 on 2025-11-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='collage_level',
            field=models.CharField(choices=[('Básico Completo', 'Básico Completo'), ('Básico Incompleto', 'Básico Incompleto'), ('Medio Completo', 'Medio Completo'), ('Medio Incompleto', 'Medio Incompleto'), ('Superior', 'Superior')], default='Básico Completo', max_length=20),
        ),
    ]
