# Generated by Django 5.2.7 on 2025-11-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_course_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional')], default='TEACHER', max_length=20),
        ),
    ]
