# Generated by Django 5.2.7 on 2025-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DIRECTOR', 'Director'), ('COORDINADOR', 'Coordinador'), ('TEACHER', 'Docente'), ('PROFESSIONAL', 'Profesional')], default='TEACHER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
